### ISSUE TITLE
Wrong LEGATO Makefile Call

### ISSUE THREAD

**Issue by GAlexMES** [mangOH/mangOH#13]
When you try to build Legato with the mangoh makefile you call the legato makefile with framework_wp85 (for example).

See: https://github.com/mangOH/mangOH/blob/713ce860c1ccd9dd4c7b8d93b875711f0c1b8b5c/Makefile#L37

But the Legato Makefile has no framework_wp85 target.

See: https://github.com/legatoproject/legato-af/blob/master/Makefile

**Comment by dpfrey** [comment]
Thanks for the report.  It looks like it was broken when Legato switched to KConfig here: https://github.com/legatoproject/legato-af/commit/096e943f4eac95e27e350c0105000add68c63ee1#diff-b67911656ef5d18c4ae36cb6741b7965L375
I will try to figure this out.

**Comment by dpfrey** [comment]
The `framework_TARGET` make target was removed from Legato when they started using KConfig.  I think they're going to add those targets back into the Makefile, but there will still be a couple of releases without that target.  I'm not sure how I'm going to address that.

**Comment by dpfrey** [comment]
The `framework_TARGET` targets exist in the Legato makefile for releases 19.01.0 and 19.02.0.  There are some intermediate commits in between where this isn't the case, but I don't think that really matters too much.
