### ISSUE TITLE
BMI088 error

### ISSUE THREAD

**Issue by KuangGengLian** [mangOH/mangOH#54]
I use BMI088 drivers，when I insmod bmi088.ko and it show me this  error"bmi088 4-0068: bmi088_write(): regmap_bulk_write() failed(-6)"?

**Comment by dpfrey** [comment]
We ended up not using this device in a mangOH board, so I'm unsure what the status of the driver is. I have removed the directory in commit 661a36f so that people like yourself don't find it and waste time on it.
