### ISSUE TITLE
Broken build.

### ISSUE THREAD

**Issue by leoniloris** [mangOH/mangOH#7]
Using the VM provided by mangOH, I can't run `make red_wp76xx` inside mangOH folder.

I get this error:
`/home/mangoh/mangOH/mangOH.sdef:85:15: error: Unrecognized section name 'componentSearch'.`

Whenever I revert these 3 commits: (2496571e49d6793b7653249979bc0a19730335ce, 354e27ddc85edc7b16e3f6bafb71e3b4941d9b08, 3d5bc8b45494ed79aab98baf46ee281ff28393c2) I can run the make again.

You guys should be using tags and releases instead of making commits directly on master.

**Comment by dpfrey** [comment]
`componentSearch` in a SDEF file is a Legato 18.04.0 feature.  They mangOH code has typically evolved to depend on features available in the latest stable release of Legato.  The commit which introduces the use of this feature is 3d5bc8b45494ed79aab98baf46ee281ff28393c2.  If you need to build the mangOH SDEF against an old version of Legato, then I suggest creating a branch from the parent of that commit.
