### ISSUE TITLE
libiio-0.15 vs libiio-0.18

### ISSUE THREAD

**Issue by johnofleek** [mangOH/mangOH#70]
When I recursively checked out the project. I'm pretty sure I got libiio-0.15
The build seems to need libiio-0.18  
To workaround this I renamed   
libiio to libiio-0.15  
added libiio-0.18 [source](https://github.com/analogdevicesinc/libiio/releases) 
added symlink called libiio --> libiio-0.18

**Comment by jtchitty** [comment]
Hi, John,

I just did a clean recursive clone of  https://github.com/mangOH/mangOH, and libiio was at master, a couple of commits after 0.18.  I wonder if you need to do a 'git submodule update'?

Cheers,

--Jen

________________________________

**Comment by johnofleek** [comment]
Hi Jen

You're correct - I've no idea what I did wrong the first time.
Just tried another recursive clone and this time libiio.so.0.18 was built

Cheers

John
